version: 2.1
jobs:
  deploy:
    working_directory: ~/repo
    
    docker:
      - image: cimg/python:3.7.10

    parameters:
      env:
        type: string

    steps:
      - checkout
      - run: python --version
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy <<parameters.env>>

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          env: 'schmidt-api-prod'
          filters:
            branches:
              only:
                - master
      - deploy:
          env: 'schmidt-api-preview'
          filters:
            branches:
              only:
                - dev
