version: 2.1
jobs:
  deploy:
    working_directory: ~/repo
    
    docker:
      - image: cimg/python:3.7.10

    parameters:
      env:
        type: string
      distribution:
        type: string

    steps:
      - checkout
      - run:
          name: Install deployment dependencies
          working_directory: /
          command: |
            pip install awsebcli --upgrade

      - run:
          name: Deploy
          command: eb deploy <<parameters.env>>

      - run:
          name: Invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
            --distribution-id <<parameters.distribution>> \
            --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          env: 'schmidt-api-prod'
          distribution: 'E3KCF50FO8RLIK'
          filters:
            branches:
              only:
                - master
      - deploy:
          env: 'schmidt-api-preview'
          distribution: 'E6J9FWVEWFDBG'
          filters:
            branches:
              only:
                - dev
